### ISSUE TITLE
How to change  the path where images are stored?

### ISSUE THREAD

**Issue by lyonwang** [andrew0928/Course.Microservices.201612#1]
![image](https://cloud.githubusercontent.com/assets/1924755/21309188/3c2e89ea-c618-11e6-91ac-dbbc1f0d89a6.png)

![image](https://cloud.githubusercontent.com/assets/1924755/21309257/91517342-c618-11e6-8fdb-1ccd346b4460.png)

**Comment by andrew0928** [comment]
你這個畫面，看起來是 beta channel 的 docker for windows 才有的。這版本初次開始提供 "switch to linux / windows containers" 的選項，也因此把 windows container 版本的 docker service 給取代掉了。

取代掉之後我還沒找到在哪邊調整 docker.json, 如果你是按照 [這篇文章](https://msdn.microsoft.com/en-us/virtualization/windowscontainers/quick_start/quick_start_windows_10) 的程序啟用 windows 10 container, 那麼可以用 ``` net stop docker ``` 指令手動停掉 docker service, 自己手動執行 ``` c:\program files\docker\dockerd.exe ``` 來指定啟動服務的參數。

```dockerd --help``` 可以看到完整說明。

至於搭配 docker for windows 的調整方式，我先試看看有無方法再回覆這個 issue

**Comment by lyonwang** [comment]
根據[這篇文章](https://docs.docker.com/engine/reference/commandline/dockerd/#windows-configuration-file)的說明, 好像在C:\ProgramData\Docker\config\daemon.json可以設定啟動參數, 不過透過我在1樓po的UI來改

**Comment by lyonwang** [comment]
我發現依照[這篇文章](https://docs.microsoft.com/en-us/virtualization/windowscontainers/quick-start/quick-start-windows-10)安裝完Docker之後:
1. 啟動docker service產生C:\ProgramData\docker底下的所有檔案之後, 停止docker engine service
2. 再於C:\ProgramData\docker\config內加上daemon.json, 內容只有一行如我在1樓po的{ "graph": "D:\\DockerStore" }, 再啟動docker engine service, 會產生一堆檔案在D:\DockerStore裡
3. 這時候把C:\ProgramData\docker\config內的daemon.json複製到D:\DockerStore\config裡, 再重啟docker engine service

這樣pull下來的image才會放到D:\DockerStore裡
我猜是在D:\DockerStore產生新的config與相關檔之後,再重啟的docker就會改去吃D:\DockerStore\config\daemon.json,這時pull的images才會放到daemon.json所列的位置.
