### ISSUE TITLE
Docker installation options

### ISSUE THREAD

**Issue by lyonwang** [andrew0928/Course.Microservices.201612#2]
Hi Andrew,

我發現目前安裝Docker的方式有以下三種：
1. Download stable version of Docker for Windows
    無法透過[保哥這篇文章](http://blog.miniasp.com/post/2016/11/22/Run-Linux-and-Windows-Containers-on-Windows-10.aspx)切換 Server side Windows/Linux Container
    **請問Client 或 Server side Windows/Linux Container的差異與用途有何差別？**
2. Download beta channel of Docker for Windows
    可透過[保哥這篇文章](http://blog.miniasp.com/post/2016/11/22/Run-Linux-and-Windows-Containers-on-Windows-10.aspx)切換 Server side Windows/Linux Container
3. 依照[這篇文章](https://docs.microsoft.com/zh-tw/virtualization/windowscontainers/quick_start/quick_start_windows_10), 使用powershell安裝(docker-1.14.0-dev.zip, docker-1.13.0-dev.zip已經找不到了...)
    但是沒有UI可以使用,而且因為安裝時要用Administrator權限開啟Powershell安裝, 所以要用Administrator權限才可以執行Docker commands

** 請問我們的課程需要使用那一種安裝方式？**

**Comment by andrew0928** [comment]
我們需要用的是 "windows container", 他的可以跑的是 windows application. Docker for windows 是背後有個 Linux vm, 跑 Linux application.

兩者的差別我有整理一篇文章可以參考:
http://columns.chicken-house.net/2016/09/05/windows-container-faq/

安裝方式可參考這篇 (for win10)。中文版維護的進度落後很多，同一篇文章請參考英文版的:

https://docs.microsoft.com/en-us/virtualization/windowscontainers/quick-start/quick-start-windows-10

若要 win2016, 參考底下有連結

**Comment by lyonwang** [comment]
所以您建議用第三種方法安裝Docker？不過就沒有Toolbar 上面的 UI 可用了...

**Comment by andrew0928** [comment]
是的，用第三種方法。
GUI tools 對 windows container 的幫助不大。比如 docker for windows 有的 CPU / RAM 設定是針對 Linux VM, windows container 沒有 VM, 這些資源就是直接 share host 的資源。

後面若要接著自動化，這些命令列的指令盡早熟悉會很有幫助。

**Comment by andrew0928** [comment]
test notification for microsoft teams
